### ISSUE TITLE
Server implementation keepalive not working

### ISSUE THREAD

**Issue by TechplexEngineer** [simonvetter/modbus#11]
When connecting to a modbus client, it seems the tcp keep alives are not respected and the connection is closed prematurely.

**Comment by simonvetter** [comment]
That's correct: the server is not looking at tcp keepalives and uses a configurable timer since the last modbus request to close inactive sessions.

What's your use case for keeping long-lived modbus/tcp connections open without issuing any request?
Would setting the ServerConfiguration.Timeout parameter to a higher value work for you?
